#+TITLE: Henrique's cool C++ project template
#+AUTHOR: Henrique Silva
#+email: hcpsilva@inf.ufrgs.br
#+INFOJS_OPT:
#+PROPERTY: cache yes

So my idea here is to for once help myself and maintain a repository with a
blank C++ project so when I start, for example, an assignment I can just clone
this and copy everything inside to just start coding.

** Project structure

I've structured the template according to the following directories:

- cpp-template/ :: The main executable sources and headers directory. Here lies
                   all ~.cpp~ files, organized inside this folder in sub-folders
                   if the source-code belongs to a module or namespace.

- bin/ :: The executables directory. Here is the final resting place of the
            project targets.

- build/ :: The ~CMake~ build directory, in which rests all CMake generated
            stuff.

- cmake/ :: Folder that keeps any CMake finder functions and such.

** Build

Building is just your common CMake shenanigans:

#+begin_src shell
cd build/
cmake ..
make
#+end_src

** To-dos

- [X] Learn CMake
- [ ] Start to use Conan or whatever
